### ISSUE TITLE
Remove "closeTransaction" method

### ISSUE THREAD

**Issue by ilvalerione** [inspector-apm/inspector-java#1]
Questo metodo va eliminato:

https://github.com/inspector-apm/inspector-java/blob/3ca3cd946da1f6269f2663b942c4e94891f30044/src/main/java/dev/inspector/agent/executor/Inspector.java#L93-L97

Tieni presente che impatta sulla libreria Spring in questi due punti:
- RestInterceptor: https://github.com/inspector-apm/inspector-spring/blob/34087d3fae4a2a3c58b5893a2cf318be4a103f93/src/main/java/dev/inspector/spring/interceptors/rest/RestInterceptor.java#L44
- SchedulerInterceptor: https://github.com/inspector-apm/inspector-spring/blob/34087d3fae4a2a3c58b5893a2cf318be4a103f93/src/main/java/dev/inspector/spring/interceptors/scheduler/SchedulerInterceptor.java#L25

Sostituire con `inspector.flush();`

**Comment by elitesoftwarehouse** [comment]
pushato
