### ISSUE TITLE
Delete "getBasicTransactionInfo" method

### ISSUE THREAD

**Issue by ilvalerione** [inspector-apm/inspector-java#2]
Eliminare:

https://github.com/inspector-apm/inspector-java/blob/3ca3cd946da1f6269f2663b942c4e94891f30044/src/main/java/dev/inspector/agent/model/Transaction.java#L59-L61

**Comment by elitesoftwarehouse** [comment]
ma questo metodo però viene usato dalla classe inspector, come lo gestiamo?

**Comment by ilvalerione** [comment]
Ok rivedendo l'implementazione ho capito a cosa serve. Lasciamo così com'é.
